---
- name: debian | install mcrypt module for php
  apt: name={{apt_package}} state=installed

- name: debian | enable mcrypt module for php
  command: php5enmod {{php_mcrypt_ini_filename}}
  args:
    creates: "{{ansible_local.phpinfo_core.php_config_file_scan_dir}}/{{php_mcrypt_extension_priority}}-{{php_mcrypt_ini_filename}}.ini"
